FROM adoptopenjdk/openjdk11:latest
ENV KEYCLOAK_CLIENT null
ENV KEYCLOAK_REALM null
ENV DB_URL null
ENV DB_USER null
ENV DB_PASSWORD null
ENV KEYCLOAK_URL null
ENV KEYCLOAK_SECRET null
ENV GMAIL_USER null
ENV GMAIL_PASS null

ARG JAR_FILE=build/libs/alert-covid-service-notification-*.jar


WORKDIR /opt/app

COPY ${JAR_FILE} service_notification.jar
EXPOSE 8089
ENTRYPOINT java -DKEYCLOAK_CLIENT=$KEYCLOAK_CLIENT -DKEYCLOAK_REALM=$KEYCLOAK_REALM -DDB_URL=$DB_URL -DDB_USER=$DB_USER -DDB_PASSWORD=$DB_PASSWORD -DKEYCLOAK_URL=$KEYCLOAK_URL -DKEYCLOAK_SECRET=$KEYCLOAK_SECRET -DGMAIl_USER=$GMAIL_USER -DGMAIL_PASS=$GMAIL_PASS -jar service_notification.jar